In [57]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [149]:
df=pd.read_csv('/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [150]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [151]:
df.shape

(10000, 14)

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [153]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [154]:
df.duplicated().sum()

0

#how many left

In [155]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [156]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [157]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [158]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [160]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [162]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0

In [163]:
X=df.drop(columns=['Exited'])
y=df['Exited']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [164]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

In [165]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [168]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [169]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [182]:
model=Sequential()
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(11,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [183]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_13 (Dense)            (None, 11)                132

 dense_14 (Dense)            (None, 11)                132

 dense_15 (Dense)            (None, 1)                 12

=================================================================
Total params: 276
Trainable params: 276
Non-trainable params: 0
_________________________________________________________________

In [187]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [193]:
history=model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3143 - accuracy: 0.8670 - val_loss: 0.3384 - val_accuracy: 0.8525
Epoch 2/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3131 - accuracy: 0.8683 - val_loss: 0.3361 - val_accuracy: 0.8550
Epoch 3/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3137 - accuracy: 0.8683 - val_loss: 0.3352 - val_accuracy: 0.8556
Epoch 4/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3139 - accuracy: 0.8645 - val_loss: 0.3353 - val_accuracy: 0.8575
Epoch 5/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3131 - accuracy: 0.8683 - val_loss: 0.3345 - val_accuracy: 0.8600
Epoch 6/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3140 - accuracy: 0.8670 - val_loss: 0.3345 - val_accuracy: 0.8575
Epoch 7/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3135 - accuracy: 0.8666 - val_loss: 0.3358 - val_accuracy: 0.8575
Epoch 8/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3140 - accuracy: 0.8662 - val_loss: 0.3363 - val_accuracy: 0.8556
Epoch 9/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3137 - accuracy: 0.8687 - val_loss: 0.3369 - val_accuracy: 0.8537
Epoch 10/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3137 - accuracy: 0.8673 - val_loss: 0.3354 - val_accuracy: 0.8575
Epoch 11/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3131 - accuracy: 0.8681 - val_loss: 0.3359 - val_accuracy: 0.8575
Epoch 12/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3136 - accuracy: 0.8672 - val_loss: 0.3376 - val_accuracy: 0.8562
Epoch 13/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3137 - accuracy: 0.8684 - val_loss: 0.3368 - val_accuracy: 0.8556
Epoch 14/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3130 - accuracy: 0.8686 - val_loss: 0.3355 - val_accuracy: 0.8575
Epoch 15/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3140 - accuracy: 0.8661 - val_loss: 0.3368 - val_accuracy: 0.8562
Epoch 16/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3131 - accuracy: 0.8678 - val_loss: 0.3358 - val_accuracy: 0.8550
Epoch 17/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3132 - accuracy: 0.8672 - val_loss: 0.3379 - val_accuracy: 0.8556
Epoch 18/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3132 - accuracy: 0.8672 - val_loss: 0.3391 - val_accuracy: 0.8537
Epoch 19/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3133 - accuracy: 0.8666 - val_loss: 0.3365 - val_accuracy: 0.8562
Epoch 20/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3125 - accuracy: 0.8666 - val_loss: 0.3369 - val_accuracy: 0.8544
Epoch 21/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3134 - accuracy: 0.8669 - val_loss: 0.3364 - val_accuracy: 0.8562
Epoch 22/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3131 - accuracy: 0.8650 - val_loss: 0.3374 - val_accuracy: 0.8537
Epoch 23/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3126 - accuracy: 0.8658 - val_loss: 0.3362 - val_accuracy: 0.8600
Epoch 24/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3126 - accuracy: 0.8666 - val_loss: 0.3366 - val_accuracy: 0.8581
Epoch 25/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3129 - accuracy: 0.8692 - val_loss: 0.3356 - val_accuracy: 0.8587
Epoch 26/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3129 - accuracy: 0.8681 - val_loss: 0.3394 - val_accuracy: 0.8544
Epoch 27/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3131 - accuracy: 0.8667 - val_loss: 0.3395 - val_accuracy: 0.8562
Epoch 28/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3129 - accuracy: 0.8662 - val_loss: 0.3374 - val_accuracy: 0.8569
Epoch 29/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3131 - accuracy: 0.8673 - val_loss: 0.3378 - val_accuracy: 0.8519
Epoch 30/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3123 - accuracy: 0.8680 - val_loss: 0.3381 - val_accuracy: 0.8544
Epoch 31/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3129 - accuracy: 0.8678 - val_loss: 0.3378 - val_accuracy: 0.8550
Epoch 32/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3133 - accuracy: 0.8678 - val_loss: 0.3389 - val_accuracy: 0.8562
Epoch 33/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3134 - accuracy: 0.8680 - val_loss: 0.3367 - val_accuracy: 0.8562
Epoch 34/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3129 - accuracy: 0.8681 - val_loss: 0.3380 - val_accuracy: 0.8537
Epoch 35/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8678 - val_loss: 0.3389 - val_accuracy: 0.8544
Epoch 36/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3137 - accuracy: 0.8662 - val_loss: 0.3377 - val_accuracy: 0.8569
Epoch 37/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3128 - accuracy: 0.8656 - val_loss: 0.3360 - val_accuracy: 0.8575
Epoch 38/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3131 - accuracy: 0.8686 - val_loss: 0.3370 - val_accuracy: 0.8556
Epoch 39/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3130 - accuracy: 0.8664 - val_loss: 0.3385 - val_accuracy: 0.8537
Epoch 40/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3124 - accuracy: 0.8661 - val_loss: 0.3380 - val_accuracy: 0.8562
Epoch 41/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3130 - accuracy: 0.8670 - val_loss: 0.3375 - val_accuracy: 0.8544
Epoch 42/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3128 - accuracy: 0.8670 - val_loss: 0.3382 - val_accuracy: 0.8587
Epoch 43/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3124 - accuracy: 0.8662 - val_loss: 0.3372 - val_accuracy: 0.8581
Epoch 44/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3126 - accuracy: 0.8678 - val_loss: 0.3360 - val_accuracy: 0.8556
Epoch 45/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3123 - accuracy: 0.8659 - val_loss: 0.3383 - val_accuracy: 0.8550
Epoch 46/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3130 - accuracy: 0.8684 - val_loss: 0.3421 - val_accuracy: 0.8506
Epoch 47/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8681 - val_loss: 0.3393 - val_accuracy: 0.8575
Epoch 48/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3130 - accuracy: 0.8659 - val_loss: 0.3388 - val_accuracy: 0.8537
Epoch 49/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3127 - accuracy: 0.8669 - val_loss: 0.3379 - val_accuracy: 0.8587
Epoch 50/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3122 - accuracy: 0.8687 - val_loss: 0.3416 - val_accuracy: 0.8512
Epoch 51/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3125 - accuracy: 0.8678 - val_loss: 0.3370 - val_accuracy: 0.8575
Epoch 52/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3119 - accuracy: 0.8664 - val_loss: 0.3403 - val_accuracy: 0.8544
Epoch 53/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3123 - accuracy: 0.8678 - val_loss: 0.3373 - val_accuracy: 0.8575
Epoch 54/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3123 - accuracy: 0.8667 - val_loss: 0.3380 - val_accuracy: 0.8544
Epoch 55/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8673 - val_loss: 0.3378 - val_accuracy: 0.8556
Epoch 56/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3126 - accuracy: 0.8672 - val_loss: 0.3377 - val_accuracy: 0.8556
Epoch 57/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8683 - val_loss: 0.3387 - val_accuracy: 0.8537
Epoch 58/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3119 - accuracy: 0.8670 - val_loss: 0.3393 - val_accuracy: 0.8562
Epoch 59/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3127 - accuracy: 0.8669 - val_loss: 0.3372 - val_accuracy: 0.8556
Epoch 60/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8681 - val_loss: 0.3374 - val_accuracy: 0.8569
Epoch 61/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3127 - accuracy: 0.8670 - val_loss: 0.3369 - val_accuracy: 0.8544
Epoch 62/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8669 - val_loss: 0.3376 - val_accuracy: 0.8537
Epoch 63/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3122 - accuracy: 0.8680 - val_loss: 0.3377 - val_accuracy: 0.8575
Epoch 64/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3122 - accuracy: 0.8684 - val_loss: 0.3383 - val_accuracy: 0.8575
Epoch 65/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8672 - val_loss: 0.3370 - val_accuracy: 0.8581
Epoch 66/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3118 - accuracy: 0.8705 - val_loss: 0.3378 - val_accuracy: 0.8581
Epoch 67/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3119 - accuracy: 0.8694 - val_loss: 0.3363 - val_accuracy: 0.8556
Epoch 68/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3119 - accuracy: 0.8681 - val_loss: 0.3381 - val_accuracy: 0.8556
Epoch 69/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3114 - accuracy: 0.8658 - val_loss: 0.3391 - val_accuracy: 0.8562
Epoch 70/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3124 - accuracy: 0.8692 - val_loss: 0.3370 - val_accuracy: 0.8575
Epoch 71/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8673 - val_loss: 0.3370 - val_accuracy: 0.8562
Epoch 72/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3125 - accuracy: 0.8678 - val_loss: 0.3370 - val_accuracy: 0.8556
Epoch 73/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8680 - val_loss: 0.3391 - val_accuracy: 0.8550
Epoch 74/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3117 - accuracy: 0.8703 - val_loss: 0.3368 - val_accuracy: 0.8569
Epoch 75/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3118 - accuracy: 0.8702 - val_loss: 0.3370 - val_accuracy: 0.8550
Epoch 76/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3117 - accuracy: 0.8670 - val_loss: 0.3418 - val_accuracy: 0.8550
Epoch 77/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3126 - accuracy: 0.8689 - val_loss: 0.3381 - val_accuracy: 0.8562
Epoch 78/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8666 - val_loss: 0.3389 - val_accuracy: 0.8550
Epoch 79/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8686 - val_loss: 0.3387 - val_accuracy: 0.8569
Epoch 80/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8659 - val_loss: 0.3385 - val_accuracy: 0.8556
Epoch 81/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3114 - accuracy: 0.8673 - val_loss: 0.3391 - val_accuracy: 0.8569
Epoch 82/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3117 - accuracy: 0.8664 - val_loss: 0.3379 - val_accuracy: 0.8587
Epoch 83/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8661 - val_loss: 0.3394 - val_accuracy: 0.8556
Epoch 84/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3119 - accuracy: 0.8670 - val_loss: 0.3431 - val_accuracy: 0.8531
Epoch 85/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3123 - accuracy: 0.8666 - val_loss: 0.3377 - val_accuracy: 0.8562
Epoch 86/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3111 - accuracy: 0.8678 - val_loss: 0.3383 - val_accuracy: 0.8569
Epoch 87/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3123 - accuracy: 0.8677 - val_loss: 0.3377 - val_accuracy: 0.8562
Epoch 88/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3114 - accuracy: 0.8680 - val_loss: 0.3381 - val_accuracy: 0.8544
Epoch 89/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3118 - accuracy: 0.8672 - val_loss: 0.3419 - val_accuracy: 0.8525
Epoch 90/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3116 - accuracy: 0.8672 - val_loss: 0.3383 - val_accuracy: 0.8556
Epoch 91/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8678 - val_loss: 0.3390 - val_accuracy: 0.8575
Epoch 92/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3119 - accuracy: 0.8659 - val_loss: 0.3398 - val_accuracy: 0.8537
Epoch 93/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3116 - accuracy: 0.8673 - val_loss: 0.3386 - val_accuracy: 0.8550
Epoch 94/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3113 - accuracy: 0.8662 - val_loss: 0.3392 - val_accuracy: 0.8569
Epoch 95/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3116 - accuracy: 0.8672 - val_loss: 0.3451 - val_accuracy: 0.8525
Epoch 96/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3121 - accuracy: 0.8695 - val_loss: 0.3391 - val_accuracy: 0.8525
Epoch 97/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3117 - accuracy: 0.8678 - val_loss: 0.3403 - val_accuracy: 0.8537
Epoch 98/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3120 - accuracy: 0.8678 - val_loss: 0.3382 - val_accuracy: 0.8569
Epoch 99/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3111 - accuracy: 0.8691 - val_loss: 0.3381 - val_accuracy: 0.8575
Epoch 100/100
200/200 [==============================] - 1s 3ms/step - loss: 0.3116 - accuracy: 0.8678 - val_loss: 0.3380 - val_accuracy: 0.8537

In [177]:
model.layers[0].get_weights()

[array([[-2.69457281e-01,  1.24509558e-01, -1.62151620e-01],
        [ 7.06840575e-01, -1.78149641e+00, -1.69250059e+00],
        [ 2.40177482e-01,  1.45826742e-01, -4.35590948e-04],
        [ 1.05432861e-01, -2.11432576e-01, -5.01314163e-01],
        [ 1.02937736e-01,  4.45148982e-02,  1.89276919e-01],
        [ 7.61587406e-03,  8.60096067e-02, -3.22851539e-02],
        [-1.28678226e+00,  4.79356766e-01,  3.12309384e-01],
        [-5.39831281e-01, -4.60809320e-01,  2.25601971e-01],
        [ 5.82801700e-01, -6.70273185e-01, -2.08179817e-01],
        [-4.51611638e-01, -6.05447181e-02, -3.70310664e-01],
        [-5.02791166e-01,  5.06074667e-01,  2.62323022e-01]], dtype=float32),
 array([-0.04055355, -0.02345678, -0.1922706 ], dtype=float32)]

In [190]:
 y_log=model.predict(X_test_scaled)

63/63 [==============================] - 0s 1ms/step

In [191]:
y_pred=np.where(y_log>0.5,1,0)

In [192]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8595